name: Build Wheels

on:
  push:
    branches:
      - main
    paths:
      - '.github/run-build-wheels'

jobs:
  build_wheels:
    name: Build wheel
    runs-on: ubuntu-18.04

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v1
        name: Install Python
        with:
          python-version: '3.8'

      - name: Install cibuildwheel
        run: |
          python -m pip install cibuildwheel
      - name: Build wheels
        env:
          CIBW_BEFORE_BUILD: bash scripts/before_ci_build.sh
          CIBW_BUILD: cp3?-*
          CIBW_SKIP: pp*
        run: |
          python -m cibuildwheel --output-dir wheelhouse

      - uses: actions/upload-artifact@v1
        with:
          name: wheels
          path: ./wheelhouse
