name: Build Wheels

on:
  workflow_dispatch:
    inputs:
      reason:
        description: 'Reason'
        required: true

jobs:
  build_wheels:
    name: Build wheel
    runs-on: ubuntu-18.04

    steps:
      - run: |
         echo "Reason for running: ${{ github.event.inputs.reason }}"
         echo "dir: $(pwd) | $(ls)"
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v1
        name: Install Python
        with:
          python-version: '3.8'

      - name: Install cibuildwheel
        run: |
          python -m pip install cibuildwheel
      - name: Build wheels
        env:
          CIBW_BEFORE_BUILD: bash .github/scripts/install_gmp.sh
          CIBW_BUILD: cp3?-*
          CIBW_SKIP: pp*
          CIBW_MANYLINUX_X86_64_IMAGE: manylinux2014
        run: |
          python -m cibuildwheel --output-dir wheelhouse

      - uses: actions/upload-artifact@v1
        with:
          name: wheels
          path: ./wheelhouse
